# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async
  polling_interval: 0.1     # 0.1 s
  message_retention: 86400  # 1 día en segundos

test:
  adapter: async
  polling_interval: 0.1     # 0.1 s
  message_retention: 86400  # 1 día en segundos

production:
  adapter: async
  polling_interval: 0.1     # 0.1 s
  message_retention: 86400  # 1 día en segundos

staging:
  adapter: async
  polling_interval: 0.1     # 0.1 s
  message_retention: 86400  # 1 día en segundos
